### ISSUE TITLE
Lantern works with no chained proxies but it requires at least one trusted fronted server

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2623]
I confirmed Lantern works with no chained proxies:

```
  frontedservers:
  - host: nl.fallbacks.getiantem.org
    port: 443
    poolsize: 30
    masqueradeset: cloudflare
    maxmasquerades: 20
    insecureskipverify: false
    bufferrequests: false
    dialtimeoutmillis: 0
    redialattempts: 2
    weight: 4000
    qos: 10
    trusted: true
  chainedservers: {}
```

But if we mark the fallback server as not trusted it starts throwing 500.
