### ISSUE TITLE
A problem for chainedservers, bug or function?

### ISSUE THREAD

**Issue by gwdgithubnom** [getlantern/lantern#5296]
I donn't kown why my lantern cann't ping the chainedservices.
I have found the yaml config include about the server ip. But i can't ping the server.

> I used fedora os, and f24. Is there some programer could help me to slove the question. 
> Here is server ip: [IP redacted by @aranhoide]:443.

```
chainedservers:
    fp-obfs4-vltok1-20160916-475:
      addr: [IP redacted by @aranhoide]:443
      cert: E9DpebCepgLjjRxvToRoKbIQkYLu1bOT/ocebIpHRAo84PxmeKs6jmMIVZS1g7CjnixfAw
      authtoken: aJhFnuc4GUMaXiAVz2TEFExOdwZ3H6YJCuUYzugGnEuxpUliE5F9tdyI8nUCvxkx
      trusted: true
      pluggabletransport: obfs4
      pluggabletransportsettings:
        iat-mode: "0"
```

> Any way, why my friends's lantern can get a different chianedservers? Is there something about .....???
> Thank you for reading about this issue.

*_Infor: when i want to change the yaml file, the lantern would change it back, is there anyone to answer this problem? *_
